server:
  port: 8080

spring:
  application:
    name: API-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/