server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: technic-service-route
          uri: lb://technic-service
          predicates:
            - Path=/api/v1/technics/**
          filters:
            - AddResponseHeader=X-Powered-By, Technic Gateway Service

    discovery:
      locator:
        enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true
