server:
  port: 8080

spring:
  application:
    name: API-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: technic-service-route
          uri: lb://technic-service
          predicates:
            - Path=/api/v1/technics/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/